@echo off
echo Starting Backend Services...

echo Starting Authentication Service...
start "Authentication Service" cmd /k "cd backend\authentication && mvn spring-boot:run"

echo Starting Time Service...
start "Time Service" cmd /k "cd backend\time-service && dotnet run"

echo Starting Calendar Service...
start "Calendar Service" cmd /k "cd backend\calendar-service && .\venv\Scripts\activate && uvicorn main:app --reload"

echo Starting Frontend Services...

echo Starting Shell Application...
start "Shell" cmd /k "cd frontend && ng serve shell"

echo Starting Auth Microfrontend...
start "Auth" cmd /k "cd frontend && ng serve auth"

echo Starting Worktime Microfrontend...
start "Worktime" cmd /k "cd frontend && ng serve worktime"

echo Starting Weekly Summary Microfrontend...
start "Weekly Summary" cmd /k "cd frontend && ng serve weekly-summary"

echo Starting Calendar Microfrontend...
start "Calendar" cmd /k "cd frontend && ng serve calendar"

echo All services started. You can close this window.
